spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
      database: journaldb
#      username: ujjwal@stylishop.com
#      password: Mongo@123
      auto-index-creation: true
      uri: mongodb+srv://ujjwal_db_user:6demryp8IyhF1KQV@cluster0.ektdcig.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 7070
#  servlet:
#    context-path: /journal